### ISSUE TITLE
作者还在吗?这个项目很好呀为啥blog不维护了

### ISSUE THREAD

**Issue by Zest-Zhang** [yxl720/vue-node#2]

**Comment by Yxliam** [comment]
哈哈，因为这个项目比较久了没有维护，有什么建议可以提出来的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yxliam/vue-node"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月12日(星期三) 凌晨2:01
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Yxliam/vue-node] 作者还在吗?这个项目很好呀为啥blog不维护了 (Issue #2)





 
Closed #2 as completed.
